FROM node:21 AS build

WORKDIR /app

COPY client/package.json client/yarn.lock ./
RUN yarn install

COPY client/ ./
COPY CHANGELOG.md ./
RUN yarn build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]